import {experiments} from './experiments.mjs';
export const rad=d=>d*Math.PI/180;
export const fmt=(n,d=2)=>Number.isFinite(n)?Number(n.toFixed(d)).toLocaleString('en-US',{maximumFractionDigits:d}):'—';
export function validate(slug,v,mode){const t=experiments.find(t=>t.slug===slug);if(!t)throw Error('Unknown experiment.');for(const f of t.fields){if(!Number.isFinite(v[f.key])||v[f.key]<f.min||v[f.key]>f.max)throw Error(`${f.label} must be between ${f.min} and ${f.max} ${f.unit}.`);}if(t.modes&&!t.modes.some(([id])=>id===mode))throw Error('Choose a valid circuit mode.');return t;}
export function calculate(slug,v,progress=0,mode='series'){
 validate(slug,v,mode);if(!Number.isFinite(progress)||progress<0||progress>1)throw Error('Time must lie within the experiment.');
 const metrics=[],steps=[];let model={},duration=1;
 const m=(label,value,unit='')=>metrics.push({label,value:typeof value==='number'?fmt(value,3):value,unit});
 if(slug==='projectile-motion'){const vx=v.speed*Math.cos(rad(v.angle)),vy=v.speed*Math.sin(rad(v.angle));duration=2*vy/v.g;const range=vx*duration,peak=vy*vy/(2*v.g),t=progress*duration;model={vx,vy,range,peak,t,x:vx*t,y:Math.max(0,vy*t-.5*v.g*t*t),g:v.g};m('Range',range,'m');m('Peak height',peak,'m');m('Flight time',duration,'s');m('Horizontal speed',vx,'m/s');steps.push(`Horizontal velocity = ${v.speed} cos(${v.angle}°) = ${fmt(vx)} m/s.`,`Vertical launch velocity = ${v.speed} sin(${v.angle}°) = ${fmt(vy)} m/s.`,`Flight time = 2vᵧ/g = ${fmt(duration)} s. Range = vₓ × time = ${fmt(range)} m.`);}
 if(slug==='motion-graphs'){duration=v.duration;const t=progress*duration,x=v.v0*t+.5*v.a*t*t,velocity=v.v0+v.a*t;model={...v,t,x,velocity};m('Time',t,'s');m('Position',x,'m');m('Velocity',velocity,'m/s');m('Acceleration',v.a,'m/s²');steps.push(`At t = ${fmt(t)} s: x = ${v.v0} × t + ½ × ${v.a} × t² = ${fmt(x)} m.`,`v = ${v.v0} + ${v.a} × ${fmt(t)} = ${fmt(velocity)} m/s.`,`End displacement at ${duration} s = ${fmt(v.v0*duration+.5*v.a*duration**2)} m.`);}
 if(slug==='force-and-friction'){const normal=v.mass*9.81,limit=v.mu*normal,friction=Math.min(v.force,limit),net=v.force-friction,acceleration=net/v.mass;model={...v,normal,limit,friction,net,acceleration};m('Friction',friction,'N');m('Net force',net,'N');m('Acceleration',acceleration,'m/s²');m('State',net>1e-10?'Sliding':'At rest');steps.push(`Normal force N = mg = ${v.mass} × 9.81 = ${fmt(normal)} N.`,`Maximum static friction = μN = ${fmt(limit)} N. Actual opposing friction = ${fmt(friction)} N.`,`Net force = ${v.force} − ${fmt(friction)} = ${fmt(net)} N. Acceleration = Fnet/m = ${fmt(acceleration)} m/s².`);}
 if(slug==='energy-conservation'){const length=v.height/Math.sin(rad(v.angle)),a=9.81*Math.sin(rad(v.angle));duration=Math.sqrt(2*length/a);const t=progress*duration,s=.5*a*t*t,h=Math.max(0,v.height-s*Math.sin(rad(v.angle))),speed=a*t,total=v.mass*9.81*v.height,potential=v.mass*9.81*h,kinetic=total-potential;model={...v,length,t,s,h,speed,total,potential,kinetic};m('Height',h,'m');m('Speed',speed,'m/s');m('Kinetic energy',kinetic,'J');m('Potential energy',potential,'J');steps.push(`Total energy = mgh₀ = ${v.mass} × 9.81 × ${v.height} = ${fmt(total)} J.`,`At height ${fmt(h)} m, potential energy = ${fmt(potential)} J. Kinetic energy = ${fmt(total)} − ${fmt(potential)} = ${fmt(kinetic)} J.`,`Speed = √(2g(h₀ − h)) = ${fmt(speed)} m/s. Travel time to the bottom = ${fmt(duration)} s.`);}
 if(slug==='pendulum'){const period=2*Math.PI*Math.sqrt(v.length/v.g);duration=2*period;const t=progress*duration,theta=v.amplitude*Math.cos(2*Math.PI*t/period);model={...v,period,t,theta};m('Period',period,'s');m('Frequency',1/period,'Hz');m('Angle now',theta,'°');m('Length',v.length,'m');steps.push(`T = 2π√(L/g) = 2π√(${v.length}/${v.g}) = ${fmt(period)} s.`,`Frequency = 1/T = ${fmt(1/period,3)} Hz.`,`Small-angle motion: θ(t) = ${v.amplitude} cos(2πt/T) degrees.`);}
 if(slug==='spring-oscillator'){const omega=Math.sqrt(v.k/v.mass),period=2*Math.PI/omega;duration=2*period;const t=progress*duration,x=v.amplitude*Math.cos(omega*t),velocity=-v.amplitude*omega*Math.sin(omega*t),potential=.5*v.k*x*x,kinetic=.5*v.mass*velocity**2,total=.5*v.k*v.amplitude**2;model={...v,t,x,velocity,potential,kinetic,total};m('Period',period,'s');m('Displacement',x,'m');m('Velocity',velocity,'m/s');m('Total energy',total,'J');steps.push(`Angular frequency = √(k/m) = ${fmt(omega)} rad/s. Period = 2π/ω = ${fmt(period)} s.`,`Spring energy = ½kx² = ${fmt(potential)} J. Kinetic energy = ½mv² = ${fmt(kinetic)} J.`,`Their sum remains ½kA² = ${fmt(total)} J.`);}
 if(slug==='wave-explorer'){const speed=v.wavelength*v.frequency,period=1/v.frequency;duration=2*period;model={...v,t:progress*duration,speed};m('Wave speed',speed,'m/s');m('Period',period,'s');m('Wavelength',v.wavelength,'m');m('Frequency',v.frequency,'Hz');steps.push(`Wave speed = frequency × wavelength = ${v.frequency} × ${v.wavelength} = ${fmt(speed)} m/s.`,`Period = 1/f = ${fmt(period)} s.`,`Particle displacement is y = ${v.amplitude} sin(2π(x/${v.wavelength} − ${v.frequency}t)).`);}
 if(slug==='ohms-law'){const current=v.voltage/v.resistance,power=v.voltage*current;model={...v,current,power};m('Current',current,'A');m('Power',power,'W');m('Voltage',v.voltage,'V');m('Resistance',v.resistance,'Ω');steps.push(`I = V/R = ${v.voltage}/${v.resistance} = ${fmt(current,3)} A.`,`P = VI = ${v.voltage} × ${fmt(current,3)} = ${fmt(power,3)} W.`);}
 if(slug==='resistor-circuits'){const parallel=mode==='parallel',resistance=parallel?1/(1/v.r1+1/v.r2):v.r1+v.r2,current=v.voltage/resistance,i1=parallel?v.voltage/v.r1:current,i2=parallel?v.voltage/v.r2:current,v1=i1*v.r1,v2=i2*v.r2;model={...v,parallel,resistance,current,i1,i2,v1,v2};m('Equivalent R',resistance,'Ω');m('Total current',current,'A');m('Current R₁',i1,'A');m('Current R₂',i2,'A');steps.push(parallel?`1/R = 1/${v.r1} + 1/${v.r2}; R = ${fmt(resistance)} Ω.`:`R = ${v.r1} + ${v.r2} = ${fmt(resistance)} Ω.`,`Total current = ${v.voltage}/${fmt(resistance)} = ${fmt(current,3)} A.`,`Voltage drops: V₁ = ${fmt(v1)} V; V₂ = ${fmt(v2)} V.`);}
 if(slug==='refraction'){const ratio=v.n1*Math.sin(rad(v.angle))/v.n2,tir=ratio>1+1e-12,refracted=tir?null:Math.asin(Math.min(1,ratio))*180/Math.PI,critical=v.n1>v.n2?Math.asin(v.n2/v.n1)*180/Math.PI:null;model={...v,tir,refracted,critical};m('Refracted angle',tir?'No transmitted ray':fmt(refracted)+'°','');m('Critical angle',critical===null?'Not applicable':fmt(critical)+'°');m('Incident angle',v.angle,'°');m('Behavior',tir?'Total internal reflection':'Transmission');steps.push(`sin θ₂ = n₁ sin θ₁ / n₂ = ${fmt(ratio,4)}.`,tir?'This exceeds 1, so no refracted ray is possible: total internal reflection.':`θ₂ = arcsin(${fmt(ratio,4)}) = ${fmt(refracted)}° from the normal.`,critical===null?'Total internal reflection is not possible in this direction.':`Critical angle = arcsin(n₂/n₁) = ${fmt(critical)}°.`);}
 if(slug==='thin-lens'){const atFocus=Math.abs(v.distance-v.f)<1e-9,image=atFocus?null:v.f*v.distance/(v.distance-v.f),magnification=atFocus?null:-image/v.distance;model={...v,image,magnification,atFocus};m('Image distance',atFocus?'No finite image':fmt(image),atFocus?'':'cm');m('Magnification',atFocus?'Undefined':fmt(magnification),'');m('Image type',atFocus?'Parallel rays':image>0?'Real':'Virtual');m('Orientation',atFocus?'—':magnification<0?'Inverted':'Upright');steps.push(`1/dᵢ = 1/${v.f} − 1/${v.distance} = ${fmt(1/v.f-1/v.distance,5)} cm⁻¹.`,atFocus?'The object is at the focal point; outgoing rays are parallel.':`Image distance = ${fmt(image)} cm. Magnification = −dᵢ/dₒ = ${fmt(magnification)}.`,atFocus?'There is no finite image height.':`Image height = M × hₒ = ${fmt(magnification*v.height)} cm.`);}
 if(slug==='buoyancy'){const volume=v.volume/1000,submerged=volume*v.fraction/100,weight=v.density*9.81*volume,buoyancy=v.fluid*9.81*submerged,net=buoyancy-weight,equilibrium=v.density/v.fluid;model={...v,weight,buoyancy,net,equilibrium};m('Buoyant force',buoyancy,'N');m('Weight',weight,'N');m('Net force (up +)',net,'N');m('Floating fraction',equilibrium>1?'Sinks':fmt(equilibrium*100)+'%');steps.push(`Volume = ${v.volume} L = ${volume} m³. Submerged volume = ${fmt(submerged,5)} m³.`,`Buoyancy = ρfluid g Vsubmerged = ${fmt(buoyancy)} N. Weight = ρobject g V = ${fmt(weight)} N.`,equilibrium>1?'The object is denser than the fluid: even full immersion cannot balance its weight.':`At equilibrium, submerged fraction = ρobject/ρfluid = ${fmt(equilibrium*100)}%.`);}
 return {metrics,steps,model,duration};
}
